Repository LubosD/twinkle, pull requests merged in 2020-02, with the labels that each got.

#181 Add -DDEBUG to non-release builds, to prevent uCommon from adding NDEBUG
  CMakeLists.txt
Labels: bug, external

#182 Switch Travis CI distribution to bionic
  .travis.yml
Labels: enhancement

#166 Simple fixes for two deadlocks
  src/phone.cpp
  src/phone.h
Labels: bug

#160 resolve nat_public_ip hostname for dyndns to work
  src/phone_user.cpp
Labels: enhancement, networking

#150 Prevent recursive locking of phone_users_mtx in add_phone_user()
  src/phone.cpp
  src/phone.h
Labels: GUI, bug

#144 Respond immediately to a "quit" command while in CLI mode
  src/userintf.cpp
  src/userintf.h
Labels: bug

#164 Fix QML binding loop in TextImageButton (used in incoming call popup)
  src/gui/qml/TextImageButton.qml
Labels: GUI, bug

#149 Systray icon: Always toggle visibility when clicking & Add "Show/Hide" menu entry
  src/gui/mphoneform.cpp
  src/gui/mphoneform.h
  src/gui/mphoneform.ui
Labels: GUI, bug, enhancement

#116 Add missing tests lost in the autotools to CMake transition
  CMakeLists.txt
  cmake/FindIlbc.cmake
  src/sockets/dnssrv.cpp
  src/util.cpp
  twinkle_config.h.in
Labels: bug

#147 Use a mutex in all t_sys_settings getters/setters, even bool
  src/sys_settings.cpp
Labels: code quality

#148 Add configuration option to disable incoming call popup window
  src/gui/mphoneform.cpp
  src/gui/syssettingsform.cpp
  src/gui/syssettingsform.ui
  src/sys_settings.cpp
  src/sys_settings.h
Labels: GUI, enhancement

#154 Add an option to prevent an idle session while a call is in progress
  CMakeLists.txt
  README.md
  src/gui/CMakeLists.txt
  src/gui/gui.cpp
  src/gui/gui.h
  src/gui/idlesession_inhibitor.cpp
  src/gui/idlesession_inhibitor.h
  src/gui/idlesession_manager.cpp
  src/gui/idlesession_manager.h
  src/gui/mphoneform.cpp
  src/gui/syssettingsform.cpp
  src/gui/syssettingsform.h
  src/gui/syssettingsform.ui
  src/sys_settings.cpp
  src/sys_settings.h
  twinkle_config.h.in
Labels: enhancement

#163 Support multiple WWW-Authenticate/Proxy-Authenticate headers
  src/parser/hdr_www_authenticate.cpp
Labels: SIP, bug
