Repository LubosD/twinkle, pull requests merged in 2022-06, with the labels that each got.

#278 Properly manage session timers if an early session was established
  src/dialog.cpp
Labels: SIP/SDP

#282 Use `typedef`s instead of `unsigned long` for 32-bit IPv4 addresses
  src/abstract_dialog.cpp
  src/dialog.cpp
  src/events.cpp
  src/events.h
  src/listener.cpp
  src/parser/sip_message.cpp
  src/parser/sip_message.h
  src/phone_user.cpp
  src/phone_user.h
  src/sender.cpp
  src/session.cpp
  src/sockets/connection.cpp
  src/sockets/connection.h
  src/sockets/connection_table.cpp
  src/sockets/connection_table.h
  src/sockets/ipaddr.h
  src/sockets/socket.cpp
  src/sockets/socket.h
  src/sockets/url.cpp
  src/sockets/url.h
  src/stun/stun_transaction.cpp
  src/stun/stun_transaction.h
Labels: networking

#117 Add compile-time check for C++11 regular expressions
  CMakeLists.txt
  README.md
  cmake/CheckCXX11Regex.cmake
Labels: enhancement

#225 Match all SIP headers case-insensitively
  src/parser/scanner.lxx
Labels: SIP/SDP
